URL = "/assessment"
FILE_RESPONSE = "You have uploaded wrong file. Please upload CSV file"
NAME_AGE_RESPONSE = "Name/Age key not present in file"
COLUMN_ID_RESPONSE = "Column id doesn't match with any. Please provide the right one"
MAPPING_RESPONSE = "Incorrect mapping of Name/Age column. Please provide the column id as in CSV"
SUCCESS_RESPONSE = "Successfully uploaded"